// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function arrow(f) {
  return {
          TAG: /* Func */0,
          _0: f
        };
}

var identity = {
  TAG: /* Func */0,
  _0: (function (prim) {
      return prim;
    })
};

function runF(__arrow, __arg) {
  var _acc = __arg;
  var _stack = identity;
  var _arrow = __arrow;
  while(true) {
    var arrow = _arrow;
    var stack = _stack;
    var acc = _acc;
    if (arrow.TAG) {
      _arrow = arrow._0;
      _stack = {
        TAG: /* Pipe */1,
        _0: arrow._1,
        _1: stack
      };
      continue ;
    }
    var result = Curry._1(arrow._0, acc);
    if (!stack.TAG) {
      return Curry._1(stack._0, result);
    }
    _arrow = stack._0;
    _stack = stack._1;
    _acc = result;
    continue ;
  };
}

function pipeR(arrowAb, bc) {
  return {
          TAG: /* Pipe */1,
          _0: arrowAb,
          _1: {
            TAG: /* Func */0,
            _0: bc
          }
        };
}

function pipeL(ab, arrowBc) {
  return {
          TAG: /* Pipe */1,
          _0: {
            TAG: /* Func */0,
            _0: ab
          },
          _1: arrowBc
        };
}

function composeR(arrowBc, ab) {
  return {
          TAG: /* Pipe */1,
          _0: {
            TAG: /* Func */0,
            _0: ab
          },
          _1: arrowBc
        };
}

function composeL(bc, arrowAb) {
  return {
          TAG: /* Pipe */1,
          _0: arrowAb,
          _1: {
            TAG: /* Func */0,
            _0: bc
          }
        };
}

function pipe(arrowAb, arrowBc) {
  return {
          TAG: /* Pipe */1,
          _0: arrowAb,
          _1: arrowBc
        };
}

function compose(arrowBc, arrowAb) {
  return {
          TAG: /* Pipe */1,
          _0: arrowAb,
          _1: arrowBc
        };
}

var split = {
  TAG: /* Func */0,
  _0: (function (a) {
      return [
              a,
              a
            ];
    })
};

function unsplit(ab_c) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return Curry._2(ab_c, param[0], param[1]);
            })
        };
}

function zip2(arrowA1b1, arrowA2b2) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return [
                      runF(arrowA1b1, param[0]),
                      runF(arrowA2b2, param[1])
                    ];
            })
        };
}

function zip3(arrowA1b1, arrowA2b2, arrowA3b3) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return [
                      runF(arrowA1b1, param[0]),
                      runF(arrowA2b2, param[1]),
                      runF(arrowA3b3, param[2])
                    ];
            })
        };
}

function zip4(arrowA1b1, arrowA2b2, arrowA3b3, arrowA4b4) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return [
                      runF(arrowA1b1, param[0]),
                      runF(arrowA2b2, param[1]),
                      runF(arrowA3b3, param[2]),
                      runF(arrowA4b4, param[3])
                    ];
            })
        };
}

function first(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return [
                      runF(arrowAb, param[0]),
                      param[1]
                    ];
            })
        };
}

function second(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (param) {
              return [
                      param[0],
                      runF(arrowAb, param[1])
                    ];
            })
        };
}

function left(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (eitherAc) {
              if (eitherAc.TAG) {
                return {
                        TAG: /* Right */1,
                        _0: eitherAc._0
                      };
              } else {
                return {
                        TAG: /* Left */0,
                        _0: runF(arrowAb, eitherAc._0)
                      };
              }
            })
        };
}

function right(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (eitherAc) {
              if (eitherAc.TAG) {
                return {
                        TAG: /* Right */1,
                        _0: runF(arrowAb, eitherAc._0)
                      };
              } else {
                return {
                        TAG: /* Left */0,
                        _0: eitherAc._0
                      };
              }
            })
        };
}

function okChannel(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (resultAc) {
              if (resultAc.TAG) {
                return {
                        TAG: /* Error */1,
                        _0: resultAc._0
                      };
              } else {
                return {
                        TAG: /* Ok */0,
                        _0: runF(arrowAb, resultAc._0)
                      };
              }
            })
        };
}

function errorChannel(arrowAb) {
  return {
          TAG: /* Func */0,
          _0: (function (resultAc) {
              if (resultAc.TAG) {
                return {
                        TAG: /* Error */1,
                        _0: runF(arrowAb, resultAc._0)
                      };
              } else {
                return {
                        TAG: /* Ok */0,
                        _0: resultAc._0
                      };
              }
            })
        };
}

function loop(arrowAc_bc, c) {
  return {
          TAG: /* Func */0,
          _0: (function (a) {
              return runF(arrowAc_bc, [
                            a,
                            c
                          ])[0];
            })
        };
}

function map(arrowAb, ab_cd) {
  var ab = function (param) {
    return runF(arrowAb, param);
  };
  var cd = Curry._1(ab_cd, ab);
  return {
          TAG: /* Func */0,
          _0: cd
        };
}

function apply(arrowAb_cd, arrowAb) {
  var ab = function (param) {
    return runF(arrowAb, param);
  };
  var cd = runF(arrowAb_cd, ab);
  return {
          TAG: /* Func */0,
          _0: cd
        };
}

function bind(arrowAb, ab_arrowCd) {
  return Curry._1(ab_arrowCd, (function (param) {
                return runF(arrowAb, param);
              }));
}

function lift(fToG, arrowF) {
  return {
          TAG: /* Func */0,
          _0: (function (arg) {
              return Curry._2(fToG, (function (param) {
                            return runF(arrowF, param);
                          }), arg);
            })
        };
}

function lift2(fToGToH, arrowF, arrowG) {
  return {
          TAG: /* Func */0,
          _0: (function (arg) {
              return Curry._3(fToGToH, (function (param) {
                            return runF(arrowF, param);
                          }), (function (param) {
                            return runF(arrowG, param);
                          }), arg);
            })
        };
}

var Impl_Infix = {
  $great$great$caret: pipeR,
  $caret$great$great: pipeL,
  $less$less$caret: composeR,
  $caret$less$less: composeL,
  $great$great$great: pipe,
  $less$less$less: compose,
  $less$$great: map,
  $less$star$great: apply,
  $great$great$eq: bind
};

var Impl = {
  identity: identity,
  returnA: identity,
  runF: runF,
  pipeR: pipeR,
  pipeL: pipeL,
  composeR: composeR,
  composeL: composeL,
  pipe: pipe,
  compose: compose,
  first: first,
  second: second,
  loop: loop,
  split: split,
  unsplit: unsplit,
  left: left,
  right: right,
  okChannel: okChannel,
  errorChannel: errorChannel,
  zip2: zip2,
  zip3: zip3,
  zip4: zip4,
  arrow: arrow,
  pure: arrow,
  map: map,
  apply: apply,
  join: runF,
  bind: bind,
  lift: lift,
  lift2: lift2,
  Infix: Impl_Infix
};

var returnA = identity;

var pure = arrow;

var join = runF;

var Infix = Impl_Infix;

exports.Impl = Impl;
exports.identity = identity;
exports.returnA = returnA;
exports.runF = runF;
exports.pipeR = pipeR;
exports.pipeL = pipeL;
exports.composeR = composeR;
exports.composeL = composeL;
exports.pipe = pipe;
exports.compose = compose;
exports.first = first;
exports.second = second;
exports.loop = loop;
exports.split = split;
exports.unsplit = unsplit;
exports.left = left;
exports.right = right;
exports.okChannel = okChannel;
exports.errorChannel = errorChannel;
exports.zip2 = zip2;
exports.zip3 = zip3;
exports.zip4 = zip4;
exports.arrow = arrow;
exports.pure = pure;
exports.map = map;
exports.apply = apply;
exports.join = join;
exports.bind = bind;
exports.lift = lift;
exports.lift2 = lift2;
exports.Infix = Infix;
/* No side effect */
