// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var identity = {
  TAG: /* Func */0,
  _0: (function (prim) {
      return prim;
    })
};

function $$eval(__arrow, __arg) {
  var _acc = __arg;
  var _stack = identity;
  var _arrow = __arrow;
  while(true) {
    var arrow = _arrow;
    var stack = _stack;
    var acc = _acc;
    if (arrow.TAG) {
      _arrow = arrow._0;
      _stack = {
        TAG: /* Pipe */1,
        _0: arrow._1,
        _1: stack
      };
      continue ;
    }
    var result = Curry._1(arrow._0, acc);
    if (!stack.TAG) {
      return Curry._1(stack._0, result);
    }
    _arrow = stack._0;
    _stack = stack._1;
    _acc = result;
    continue ;
  };
}

function pipeR(arrow_ab, bc) {
  return {
          TAG: /* Pipe */1,
          _0: arrow_ab,
          _1: {
            TAG: /* Func */0,
            _0: bc
          }
        };
}

function pipeL(ab, arrow_bc) {
  return {
          TAG: /* Pipe */1,
          _0: {
            TAG: /* Func */0,
            _0: ab
          },
          _1: arrow_bc
        };
}

function composeR(arrow_bc, ab) {
  return {
          TAG: /* Pipe */1,
          _0: {
            TAG: /* Func */0,
            _0: ab
          },
          _1: arrow_bc
        };
}

function composeL(bc, arrow_ab) {
  return {
          TAG: /* Pipe */1,
          _0: arrow_ab,
          _1: {
            TAG: /* Func */0,
            _0: bc
          }
        };
}

function concat(arrowF, arrowG) {
  return {
          TAG: /* Pipe */1,
          _0: arrowF,
          _1: arrowG
        };
}

function pure(f) {
  return {
          TAG: /* Func */0,
          _0: f
        };
}

function map(arrowF, fToG) {
  var f = function (param) {
    return $$eval(arrowF, param);
  };
  var g = Curry._1(fToG, f);
  return {
          TAG: /* Func */0,
          _0: g
        };
}

function apply(arrowFF, arrowG) {
  var g = function (param) {
    return $$eval(arrowG, param);
  };
  return {
          TAG: /* Func */0,
          _0: $$eval(arrowFF, g)
        };
}

function bind(arrowF, fToArrowG) {
  var f = function (param) {
    return $$eval(arrowF, param);
  };
  var arrowG = Curry._1(fToArrowG, f);
  var g = function (param) {
    return $$eval(arrowG, param);
  };
  return {
          TAG: /* Func */0,
          _0: g
        };
}

function lift(fToG, arrowF) {
  return {
          TAG: /* Func */0,
          _0: (function (arg) {
              return Curry._2(fToG, (function (param) {
                            return $$eval(arrowF, param);
                          }), arg);
            })
        };
}

function lift2(fToGToH, arrowF, arrowG) {
  return {
          TAG: /* Func */0,
          _0: (function (arg) {
              return Curry._3(fToGToH, (function (param) {
                            return $$eval(arrowF, param);
                          }), (function (param) {
                            return $$eval(arrowG, param);
                          }), arg);
            })
        };
}

var Infix = {
  $caret$great$great: pipeL,
  $great$great$caret: pipeR,
  $caret$less$less: composeL,
  $less$less$caret: composeR,
  $less$$great: map,
  $less$star$great: apply,
  $great$great$eq: bind
};

var Impl = {
  identity: identity,
  $$eval: $$eval,
  pipeR: pipeR,
  pipeL: pipeL,
  composeR: composeR,
  composeL: composeL,
  concat: concat,
  merge: concat,
  pure: pure,
  join: $$eval,
  map: map,
  apply: apply,
  bind: bind,
  lift: lift,
  lift2: lift2,
  Infix: Infix
};

var merge = concat;

var join = $$eval;

exports.Impl = Impl;
exports.identity = identity;
exports.$$eval = $$eval;
exports.pipeR = pipeR;
exports.pipeL = pipeL;
exports.composeR = composeR;
exports.composeL = composeL;
exports.concat = concat;
exports.merge = merge;
exports.pure = pure;
exports.join = join;
exports.map = map;
exports.apply = apply;
exports.bind = bind;
exports.lift = lift;
exports.lift2 = lift2;
exports.Infix = Infix;
/* No side effect */
