// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function left(x) {
  return {
          TAG: /* Left */0,
          _0: x
        };
}

function right(x) {
  return {
          TAG: /* Right */1,
          _0: x
        };
}

function mapLeft(either, aToC) {
  if (either.TAG) {
    return {
            TAG: /* Right */1,
            _0: either._0
          };
  } else {
    return {
            TAG: /* Left */0,
            _0: Curry._1(aToC, either._0)
          };
  }
}

function mapRight(either, bToC) {
  if (either.TAG) {
    return {
            TAG: /* Right */1,
            _0: Curry._1(bToC, either._0)
          };
  } else {
    return {
            TAG: /* Left */0,
            _0: either._0
          };
  }
}

var Impl = {
  left: left,
  right: right,
  mapLeft: mapLeft,
  mapRight: mapRight
};

exports.Impl = Impl;
exports.left = left;
exports.right = right;
exports.mapLeft = mapLeft;
exports.mapRight = mapRight;
/* No side effect */
