// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Arrow = require("./Arrow.js");

function add(a, b) {
  return a + b | 0;
}

function sub(a, b) {
  return a - b | 0;
}

function fib(n, cont) {
  if (n < 3) {
    return Arrow.$$eval(cont, 1);
  } else {
    return Arrow.$$eval(cont, n - 1 | 0) + Arrow.$$eval(cont, n - 2 | 0) | 0;
  }
}

function fib$1(__x) {
  return fib(__x, Arrow.pure(function (__x) {
                  return fib(__x, Arrow.identity);
                }));
}

var a = fib$1(1);

var b = fib$1(4);

var c = fib$1(6);

var d = fib$1(10);

console.log(a, b, c, d);

exports.add = add;
exports.sub = sub;
exports.fib = fib$1;
exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
/* a Not a pure module */
