// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Arrow = require("../src/Arrow.js");
var Curry = require("bs-platform/lib/js/curry.js");

function addFloat(a, b) {
  return a + b;
}

function subFloat(a, b) {
  return a - b;
}

function mulFloat(a, b) {
  return a * b;
}

function divFloat(a, b) {
  return a / b;
}

function useIntegersInstead(fn, a) {
  return Curry._1(fn, a) | 0;
}

var __x = Arrow.pipeR(Arrow.pipeR(Arrow.pipeR(Arrow.pure(function (__x) {
                  return __x + 4;
                }), (function (__x) {
                return __x * 3;
              })), (function (__x) {
            return __x - 4;
          })), (function (__x) {
        return __x / 1;
      }));

var myArrow = Arrow.map(__x, (function (__x) {
        return function (param) {
          return Curry._1(__x, param) | 0;
        };
      }));

var result = Arrow.$$eval(myArrow, 0);

exports.addFloat = addFloat;
exports.subFloat = subFloat;
exports.mulFloat = mulFloat;
exports.divFloat = divFloat;
exports.useIntegersInstead = useIntegersInstead;
exports.myArrow = myArrow;
exports.result = result;
/* __x Not a pure module */
