// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Arrow = require("../src/Arrow.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function add(a, b) {
  return a + b | 0;
}

function sub(a, b) {
  return a - b | 0;
}

function mul(a, b) {
  return Math.imul(a, b);
}

var div = Caml_int32.div;

var myArrow = Arrow.pipeR(Arrow.pipeR(Arrow.pipeR(Arrow.pure(function (__x) {
                  return __x + 4 | 0;
                }), (function (__x) {
                return Math.imul(__x, 3);
              })), (function (__x) {
            return __x - 4 | 0;
          })), (function (__x) {
        return __x / 1 | 0;
      }));

var result = Arrow.$$eval(myArrow, 0);

console.log(result);

exports.add = add;
exports.sub = sub;
exports.mul = mul;
exports.div = div;
exports.myArrow = myArrow;
exports.result = result;
/* myArrow Not a pure module */
